# Default values for oai-physim.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  serviceAccountName: oai-physim-sa
  namespace: "OAICICD_PROJECT"
  image:
    registry: local
    repository: image-registry.openshift-image-registry.svc:5000/oaicicd-ran/oai-physim
    version: TAG
    # pullPolicy: IfNotPresent or Never or Always
    pullPolicy: Always

## Declaring values specific to coressponding physim to overwrite

dlsim.basic:
  replicaCount: 1
  service:
    type: ClusterIP
    port: 80

dlsim.100rb+tm2:
  replicaCount: 1
  service:
    type: ClusterIP
    port: 80

ulsim:
  replicaCount: 1
  service:
    type: ClusterIP
    port: 80

ldpctest:
  replicaCount: 1
  service:
    type: ClusterIP
    port: 80

polartest:
  replicaCount: 1
  service:
    type: ClusterIP
    port: 80

nr-pbchsim.106rb:
  replicaCount: 1
  service:
    type: ClusterIP
    port: 80

nr-pbchsim.217rb:
  replicaCount: 1
  service:
    type: ClusterIP
    port: 80

nr-pbchsim.273rb:
  replicaCount: 1
  service:
    type: ClusterIP
    port: 80

nr-dlsim.basic:
  replicaCount: 1
  service:
    type: ClusterIP
    port: 80

nr-dlsim.dmrs+ptrs:
  replicaCount: 1
  service:
    type: ClusterIP
    port: 80

nr-dlsim.mcs+mimo:
  replicaCount: 1
  service:
    type: ClusterIP
    port: 80

nr-dlsim.offset:
  replicaCount: 1
  service:
    type: ClusterIP
    port: 80

nr-dlschsim:
  replicaCount: 1
  service:
    type: ClusterIP
    port: 80

smallblocktest:
  replicaCount: 1
  service:
    type: ClusterIP
    port: 80

nr-ulschsim:
  replicaCount: 1
  service:
    type: ClusterIP
    port: 80

nr-pucchsim:
  replicaCount: 1
  service:
    type: ClusterIP
    port: 80

nr-ulsim.3gpp:
  replicaCount: 1
  service:
    type: ClusterIP
    port: 80

nr-ulsim.mimo:
  replicaCount: 1
  service:
    type: ClusterIP
    port: 80

nr-ulsim.misc:
  replicaCount: 1
  service:
    type: ClusterIP
    port: 80

nr-ulsim.sc-fdma:
  replicaCount: 1
  service:
    type: ClusterIP
    port: 80

nr-prachsim:
  replicaCount: 1
  service:
    type: ClusterIP
    port: 80
