version: '3.8'
services:
    oai-nrf:
        container_name: "l2sim-oai-nrf"
        image: oai-nrf:august-dev
        environment:
            - NRF_INTERFACE_NAME_FOR_SBI=eth0
            - NRF_INTERFACE_PORT_FOR_SBI=80
            - NRF_INTERFACE_HTTP2_PORT_FOR_SBI=9090
            - NRF_API_VERSION=v1
            - INSTANCE=0
            - PID_DIRECTORY=/var/run
        networks:
            public_net:
                ipv4_address: 192.168.71.130
        volumes:
            - ../5g_rfsimulator/nrf-healthcheck.sh:/openair-nrf/bin/nrf-healthcheck.sh
        healthcheck:
            test: /bin/bash -c "/openair-nrf/bin/nrf-healthcheck.sh"
            interval: 10s
            timeout: 5s
            retries: 5
    mysql:
        container_name: "l2sim-mysql"
        image: mysql:5.7
        volumes:
            - ../5g_rfsimulator/oai_db.sql:/docker-entrypoint-initdb.d/oai_db.sql
            - ../5g_rfsimulator/mysql-healthcheck.sh:/tmp/mysql-healthcheck.sh
        environment:
            - TZ=Europe/Paris
            - MYSQL_DATABASE=oai_db
            - MYSQL_USER=test
            - MYSQL_PASSWORD=test
            - MYSQL_ROOT_PASSWORD=linux
        healthcheck:
            test: /bin/bash -c "/tmp/mysql-healthcheck.sh"
            interval: 10s
            timeout: 5s
            retries: 5
        networks:
            public_net:
                ipv4_address: 192.168.71.131
    oai-amf:
        container_name: "l2sim-oai-amf"
        image: oai-amf:august-dev
        environment:
            - TZ=Europe/paris
            - INSTANCE=0
            - PID_DIRECTORY=/var/run
            - MCC=208
            - MNC=99
            - REGION_ID=128
            - AMF_SET_ID=1
            - SERVED_GUAMI_MCC_0=208
            - SERVED_GUAMI_MNC_0=99
            - SERVED_GUAMI_REGION_ID_0=128
            - SERVED_GUAMI_AMF_SET_ID_0=1
            - SERVED_GUAMI_MCC_1=460
            - SERVED_GUAMI_MNC_1=11
            - SERVED_GUAMI_REGION_ID_1=10
            - SERVED_GUAMI_AMF_SET_ID_1=1
            - PLMN_SUPPORT_MCC=208
            - PLMN_SUPPORT_MNC=99
            - PLMN_SUPPORT_TAC=0x0001
            - SST_0=1
            - SD_0=0xffffff
            - SST_1=1
            - SD_1=1
            - AMF_INTERFACE_NAME_FOR_NGAP=eth0
            - AMF_INTERFACE_NAME_FOR_N11=eth0
            - SMF_INSTANCE_ID_0=1
            - SMF_FQDN_0=oai-smf
            - SMF_IPV4_ADDR_0=0.0.0.0
            - SMF_HTTP_VERSION_0=v1
            - SELECTED_0=true
            - SMF_INSTANCE_ID_1=2
            - SMF_FQDN_1=oai-smf
            - SMF_IPV4_ADDR_1=0.0.0.0
            - SMF_HTTP_VERSION_1=v1
            - SELECTED_1=false
            - MYSQL_SERVER=192.168.71.131
            - MYSQL_USER=root
            - MYSQL_PASS=linux
            - MYSQL_DB=oai_db
            - OPERATOR_KEY=c42449363bbad02b66d16bc975d77cc1
            - NRF_IPV4_ADDRESS=192.168.71.130
            - NRF_PORT=80
            - NF_REGISTRATION=yes
            - SMF_SELECTION=yes
            - USE_FQDN_DNS=yes
            - NRF_API_VERSION=v1
            - NRF_FQDN=oai-nrf
            - EXTERNAL_AUSF=no
            - AUSF_IPV4_ADDRESS=0.0.0.0
            - AUSF_PORT=80
            - AUSF_API_VERSION=v1
            - AUSF_FQDN=localhost
        depends_on:
            - oai-nrf
            - mysql
        volumes:
            - ../5g_rfsimulator/amf-healthcheck.sh:/openair-amf/bin/amf-healthcheck.sh
        healthcheck:
            test: /bin/bash -c "/openair-amf/bin/amf-healthcheck.sh"
            interval: 10s
            timeout: 15s
            retries: 5
        networks:
            public_net:
                ipv4_address: 192.168.71.132
    oai-smf:
        container_name: "l2sim-oai-smf"
        image: oai-smf:august-dev
        environment:
            - TZ=Europe/Paris
            - INSTANCE=0
            - PID_DIRECTORY=/var/run
            - SMF_INTERFACE_NAME_FOR_N4=eth0
            - SMF_INTERFACE_NAME_FOR_SBI=eth0
            - SMF_INTERFACE_PORT_FOR_SBI=80
            - SMF_INTERFACE_HTTP2_PORT_FOR_SBI=9090
            - SMF_API_VERSION=v1
            - DEFAULT_DNS_IPV4_ADDRESS=172.21.3.100
            - DEFAULT_DNS_SEC_IPV4_ADDRESS=4.4.4.4
            - AMF_IPV4_ADDRESS=0.0.0.0
            - AMF_PORT=80
            - AMF_API_VERSION=v1
            - AMF_FQDN=oai-amf
            - UDM_IPV4_ADDRESS=127.0.0.1
            - UDM_PORT=80
            - UDM_API_VERSION=v1
            - UDM_FQDN=localhost
            - UPF_IPV4_ADDRESS=192.168.71.134
            - UPF_FQDN_0=oai-spgwu
            - NRF_IPV4_ADDRESS=192.168.71.130
            - NRF_PORT=80
            - NRF_API_VERSION=v1
            - NRF_FQDN=oai-nrf
            - REGISTER_NRF=yes
            - DISCOVER_UPF=yes
            - USE_FQDN_DNS=yes
            - DNN_NI0=oai
            - TYPE0=IPv4
            - DNN_RANGE0=12.1.1.2 - 12.1.1.127
            - NSSAI_SST0=1
            - NSSAI_SD0=0xFFFFFF
            - SESSION_AMBR_UL0=200Mbps
            - SESSION_AMBR_DL0=400Mbps
            - DNN_NI2=oai.ipv4
        depends_on:
            - oai-nrf
            - oai-amf
        volumes:
            - ../5g_rfsimulator/smf-healthcheck.sh:/openair-smf/bin/smf-healthcheck.sh
        healthcheck:
            test: /bin/bash -c "/openair-smf/bin/smf-healthcheck.sh"
            interval: 10s
            timeout: 5s
            retries: 5
        networks:
            public_net:
                ipv4_address: 192.168.71.133
    oai-spgwu:
        container_name: "l2sim-oai-spgwu"
        image: oai-spgwu-tiny:august-dev
        environment:
            - TZ=Europe/Paris
            - PID_DIRECTORY=/var/run
            - SGW_INTERFACE_NAME_FOR_S1U_S12_S4_UP=eth0
            - SGW_INTERFACE_NAME_FOR_SX=eth0
            - PGW_INTERFACE_NAME_FOR_SGI=eth0
            - NETWORK_UE_NAT_OPTION=yes
            - NETWORK_UE_IP=12.1.1.0/24
            - SPGWC0_IP_ADDRESS=192.168.71.133
            - BYPASS_UL_PFCP_RULES=no
            - MCC=208
            - MNC=99
            - MNC03=099
            - TAC=1
            - GTP_EXTENSION_HEADER_PRESENT=yes
            - GW_ID=1
            - REALM=openairinterface.org
            - ENABLE_5G_FEATURES=yes
            - REGISTER_NRF=yes
            - USE_FQDN_NRF=yes
            - UPF_FQDN_5G=oai-spgwu
            - NRF_IPV4_ADDRESS=192.168.71.130
            - NRF_PORT=80
            - NRF_API_VERSION=v1
            - NRF_FQDN=oai-nrf
            - NSSAI_SST_0=1
            - NSSAI_SD_0=0xffffff
            - DNN_0=oai
        depends_on:
            - oai-nrf
            - oai-smf
        cap_add:
            - NET_ADMIN
            - SYS_ADMIN
        cap_drop:
            - ALL
        privileged: true
        volumes:
            - ../5g_rfsimulator/spgwu-healthcheck.sh:/openair-spgwu-tiny/bin/spgwu-healthcheck.sh
        healthcheck:
            test: /bin/bash -c "/openair-spgwu-tiny/bin/spgwu-healthcheck.sh"
            interval: 10s
            timeout: 5s
            retries: 5
        networks:
            public_net:
                ipv4_address: 192.168.71.134
            traffic_net:
                ipv4_address: 192.168.72.134
    oai-ext-dn:
        image: ubuntu:bionic
        privileged: true
        container_name: "l2sim-oai-ext-dn"
        entrypoint: /bin/bash -c \
              "apt update; apt install -y procps iptables iproute2 iperf iputils-ping;"\
              "ip route add 12.1.1.0/24 via 192.168.72.134 dev eth0; sleep infinity"
        depends_on:
            - oai-spgwu
        networks:
            traffic_net:
                ipv4_address: 192.168.72.135
        healthcheck:
            test: /bin/bash -c "ping -c 2 192.168.72.134"
            interval: 10s
            timeout: 5s
            retries: 5
    oai-gnb:
        image: oai-gnb:develop
        privileged: true
        container_name: "l2sim-oai-gnb"
        network_mode: "host"
        environment:
            TZ: Europe/Paris
            USE_SA_NFAPI_VNF: 'yes'
            GNB_NAME: gnb-l2sim-vnf
            TAC: 1
            MCC: '208'
            MNC: '99'
            MNC_LENGTH: 2
            NSSAI_SST: 1
            AMF_IP_ADDRESS: 192.168.71.132
            GNB_NGA_IF_NAME: eno1
            GNB_NGA_IP_ADDRESS: 172.21.16.128
            GNB_NGU_IF_NAME: eno1
            GNB_NGU_IP_ADDRESS: 172.21.16.128
            LOCAL_S_IF_NAME: 'lo:'
            REMOTE_S_ADDRESS: 127.0.0.1
            LOCAL_S_ADDRESS: 127.0.0.2
            USE_ADDITIONAL_OPTIONS: --sa --nfapi VNF --emulate-l1 --log_config.global_log_options level,time,thread_id,nocolor
        depends_on:
            - oai-spgwu
            - oai-amf
        healthcheck:
            test: /bin/bash -c "pgrep nr-softmodem"
            interval: 10s
            timeout: 5s
            retries: 5

    proxy:
        image: oai-lte-multi-ue-proxy:latest
        privileged: true
        container_name: "l2sim-proxy"
        network_mode: "host"
        environment:
            TZ: Europe/Paris
        command: "/oai-lte-multi-ue-proxy/bin/proxy 1 --nr"
        depends_on:
            - oai-gnb
        healthcheck:
            test: /bin/bash -c "pgrep proxy"
            interval: 10s
            timeout: 5s
            retries: 5

    oai-nr-ue0:
        image: oai-nr-ue:develop
        privileged: true
        container_name: "l2sim-oai-nr-ue0"
        network_mode: "host"
        environment:
            TZ: Europe/Paris
            USE_NFAPI: 'yes'
            OPENAIR_DIR: /opt/oai-nr-ue
            FULL_IMSI: '208990100001100'
            FULL_KEY: 'fec86ba6eb707ed08905757b1bb44b8f'
            OPC: 'C42449363BBAD02B66D16BC975D77CC1'
            DNN: oai
            NSSAI_SST: 1
            NSSAI_SD: 0xffffff
            NR_UE_NFAPI_IF_NAME: eno1
            GNB_IP_ADDRESS: 127.0.0.1
            NR_UE_IP_ADDRESS: 127.0.0.1
            USE_ADDITIONAL_OPTIONS: --nokrnmod 1  --nfapi STANDALONE_PNF --node-number 2 --sa --emulate-l1 --log_config.global_log_options level,time,thread_id,nocolor
        volumes:
            - ../../../openair1/SIMULATION/LTE_PHY/BLER_SIMULATIONS/AWGN/AWGN_results:/opt/oai-nr-ue/openair1/SIMULATION/LTE_PHY/BLER_SIMULATIONS/AWGN/AWGN_results
        depends_on:
            - oai-gnb
            - proxy
        healthcheck:
            test: /bin/bash -c "pgrep nr-uesoftmodem"
            interval: 10s
            timeout: 5s
            retries: 5

networks:
    public_net:
        driver: bridge
        name: l2sim-oai-public-net
        ipam:
            config:
                - subnet: 192.168.71.128/26
        driver_opts:
            com.docker.network.bridge.name: "l2sim-public"
    traffic_net:
        driver: bridge
        name: l2sim-oai-traffic-net
        ipam:
            config:
                - subnet: 192.168.72.128/26
        driver_opts:
            com.docker.network.bridge.name: "l2sim-traffic"
